// ============================================================
// VANTAGE DQ — CORE ENTITY TYPES (Spec-Compliant v2)
// ============================================================
// Every DQ object now carries provenance, review status,
// confidence, and source lineage so the system always knows
// what the AI invented vs what the user validated.
// ============================================================

// ── Provenance ──────────────────────────────────────────────

/** Who/what created this object */
export type CreatedBy =
  | 'user'              // Typed directly by a human
  | 'ai'                // Generated by Claude with no source doc
  | 'workshop'          // Entered during a facilitated workshop session
  | 'document_extraction'; // Pulled from an uploaded document via Deep Dive

/** Lifecycle state of any DQ object */
export type ReviewStatus =
  | 'draft'             // AI-suggested, not yet seen by user
  | 'ai_suggested'      // Surfaced in review queue, awaiting decision
  | 'needs_review'      // User flagged for revisit
  | 'user_validated'    // User explicitly accepted
  | 'rejected';         // User explicitly rejected (kept for audit trail)

/** Which starting path created this session */
export type SessionSourceMode =
  | 'document_deep_dive'
  | 'blank_slate'
  | 'five_question_start'
  | 'demo';

// ── Base provenance mixin — every entity extends this ────────

export interface DQProvenance {
  createdBy: CreatedBy;
  reviewStatus: ReviewStatus;
  /** 0–1 confidence score from the AI (1 = certain, 0 = pure guess) */
  confidenceScore: number;
  /** Human-readable reference to the source: doc page, section, module id */
  sourceReference?: string;
  /** Which module produced this object (e.g. 'problem', 'issues', 'strategy') */
  sourceModule?: string;
  /** ISO timestamp of last human interaction */
  lastReviewedAt?: string;
  /** User id/email who last reviewed */
  lastReviewedBy?: string;
}

// ── Session ──────────────────────────────────────────────────

export interface Session {
  id: string;
  name: string;
  /** Which starting path was used */
  sourceMode: SessionSourceMode;
  owner_email: string;
  org_id?: string;
  created_at: string;
  updated_at: string;
  /** Snapshot of session state at key moments */
  versions?: SessionSnapshot[];
  /** Full ordered log of decisions and changes */
  auditTrail?: AuditEntry[];
  /** Structured data from the Workshop Copilot */
  workshopData?: WorkshopSession;
  /** AI decisions remembered across modules to prevent regeneration */
  decisionMemory?: DecisionMemory;
  /** Raw document text if created via Deep Dive */
  sourceDocument?: string;
  /** Module readiness states, keyed by module id */
  moduleReadiness?: Record<string, ModuleReadiness>;
}

export interface SessionSnapshot {
  timestamp: string;
  trigger: string; // e.g. "pre_deep_dive_review", "user_validated_all"
  data: Record<string, unknown>;
}

export interface AuditEntry {
  timestamp: string;
  actor: CreatedBy | string; // createdBy type or user email
  action: string;
  moduleId?: string;
  entityType?: string;
  entityId?: string;
  before?: unknown;
  after?: unknown;
}

// ── Module Readiness ─────────────────────────────────────────

export type ModuleReadinessState =
  | 'not_started'
  | 'missing_required_inputs'
  | 'draft_available'
  | 'needs_review'
  | 'ready'
  | 'validated';

export interface ModuleReadiness {
  state: ModuleReadinessState;
  missingInputs?: string[];   // Descriptions of what's needed
  draftCount?: number;        // Items waiting for review
  lastUpdated?: string;
}

// ── Problem Frame ────────────────────────────────────────────

export interface ProblemFrame extends DQProvenance {
  id: string;
  session_id: string;
  decisionStatement: string;
  context: string;
  decisionOwner?: string;
  trigger?: string;          // What prompted this decision now
  scopeIn?: string[];        // Explicitly in scope
  scopeOut?: string[];       // Explicitly out of scope
  givens?: string[];         // Fixed constraints / non-negotiables
  successCriteria: string[];
  constraints: string[];
  created_at: string;
  updated_at: string;
}

// ── Issues ───────────────────────────────────────────────────

export interface IssueEntry extends DQProvenance {
  id: string;
  session_id: string;
  label: string;
  category: string;
  description?: string;
  impact?: 'low' | 'medium' | 'high' | 'critical';
  priority?: number;
  created_at?: string;
}

// ── Decision Hierarchy ───────────────────────────────────────

export interface DecisionNode extends DQProvenance {
  id: string;
  session_id: string;
  label: string;
  type: 'big_arrow' | 'strategic' | 'tactical' | 'operational';
  parentId?: string;
  rationale?: string;
  created_at?: string;
}

// ── Strategy Table ───────────────────────────────────────────

/**
 * SINGLE SOURCE OF TRUTH — strategies must originate here.
 * Downstream modules consume strategies; they must NEVER regenerate them.
 */
export interface Strategy extends DQProvenance {
  id: string;
  session_id: string;
  name: string;
  description?: string;
  tagline?: string;
  color?: string;
  isBaseline?: boolean;
  created_at?: string;
}

// ── Qualitative Assessment ───────────────────────────────────

export interface AssessmentCriterion extends DQProvenance {
  id: string;
  session_id: string;
  label: string;
  weight: number; // 0–1
  created_at?: string;
}

export interface AssessmentScore extends DQProvenance {
  id: string;
  session_id: string;
  strategyId: string;
  criterionId: string;
  score: number; // 1–5
  rationale?: string;
}

// ── DQ Scorecard ─────────────────────────────────────────────

export interface DQDimension extends DQProvenance {
  id: string;
  session_id: string;
  dimension: 'frame' | 'alternatives' | 'information' | 'values' | 'reasoning' | 'commitment';
  score: number; // 0–100
  notes?: string;
  gaps?: string[];
}

// ── Stakeholders ─────────────────────────────────────────────

export interface StakeholderEntry extends DQProvenance {
  id: string;
  session_id: string;
  name: string;
  role?: string;
  influence: number; // 0–100
  interest: number;  // 0–100
  alignment: 'champion' | 'supporter' | 'neutral' | 'skeptic' | 'blocker';
  concerns?: string;
  engagement_action?: string;
}

// ── Risk Items ───────────────────────────────────────────────

export interface RiskItem extends DQProvenance {
  id: string;
  session_id: string;
  label: string;
  likelihood: 'Very Low' | 'Low' | 'Medium' | 'High' | 'Very High';
  impact: 'Very Low' | 'Low' | 'Medium' | 'High' | 'Very High';
  timeframe?: string;
  owner?: string;
  mitigation?: string;
  strategyId?: string; // linked strategy if applicable
}

// ── Workshop ─────────────────────────────────────────────────

export type WorkshopRole = 'facilitator' | 'participant' | 'observer';
export type WorkshopView = 'facilitator' | 'participant' | 'projector';
export type WorkshopPhase =
  | 'frame'
  | 'issues'
  | 'strategies'
  | 'assess'
  | 'align'
  | 'commit';

export interface WorkshopParticipant {
  id: string;
  name: string;
  email?: string;
  role: WorkshopRole;
  joinedAt: string;
  isOnline?: boolean;
}

export interface WorkshopSession {
  id: string;
  sessionId: string;
  facilitatorId: string;
  currentPhase: WorkshopPhase;
  currentView: WorkshopView;
  participants: WorkshopParticipant[];
  reviewQueue: ReviewQueueItem[];
  startedAt: string;
  endedAt?: string;
}

// ── Review Queue ─────────────────────────────────────────────

/** An extracted item waiting for user accept/reject before being pushed to a module */
export interface ReviewQueueItem {
  id: string;
  session_id: string;
  /** The entity type this item will become */
  targetType:
    | 'problem_frame'
    | 'issue'
    | 'decision_node'
    | 'strategy'
    | 'stakeholder'
    | 'risk_item'
    | 'criterion';
  /** The target module it will be pushed to */
  targetModule: string;
  /** The actual data payload (shape matches the target entity) */
  data: Record<string, unknown>;
  /** Confidence the AI had extracting this (0–1) */
  confidenceScore: number;
  /** Direct quote or paraphrase from source doc that supports this */
  sourceQuote?: string;
  /** Page/section reference in the source document */
  sourceReference?: string;
  /** AI's reasoning for extracting this item */
  extractionRationale?: string;
  status: 'pending' | 'accepted' | 'rejected' | 'edited';
  /** If the user edited the item before accepting, store the diff */
  userEdits?: Record<string, unknown>;
  created_at: string;
}

// ── AI Response Shape ────────────────────────────────────────

/** Full-fidelity AI response — every module response must match this shape */
export interface DQAIResult<T = unknown> {
  data: T;
  /** How much to trust this response */
  trust: 'high' | 'medium' | 'low';
  meta: {
    model: string;
    latencyMs: number;
    tokensUsed?: number;
  };
  /** Explicit list of data points the AI used to produce this response */
  dataUsed: string[];
  /** Information the AI needed but didn't have */
  missingData: string[];
  /** Assumptions the AI made that the user should validate */
  assumptionsMade: string[];
  /** Contradictions detected across modules */
  contradictions: string[];
  /** What the AI recommends the user do next */
  suggestedNextActions: string[];
  /** Per-item confidence scores if the response contains a list */
  itemConfidences?: Record<string, number>;
}

// ── Deep Dive Extraction Output ──────────────────────────────

/** All 15 extraction targets from a Deep Dive document */
export interface DeepDiveExtractionResult {
  // Session-level
  sessionName: string;
  sourceMode: 'document_deep_dive';
  confidenceScore: number;

  // Problem Frame
  decisionStatement: string;
  context: string;
  decisionOwner?: string;
  trigger?: string;
  scopeIn?: string[];
  scopeOut?: string[];
  givens?: string[];
  constraints?: string[];
  successCriteria?: string[];

  // Module seed data
  initialIssues?: Partial<IssueEntry>[];
  decisionHierarchyCandidates?: Partial<DecisionNode>[];
  strategyCandidates?: Partial<Strategy>[];
  uncertainties?: string[];
  risks?: Partial<RiskItem>[];
  stakeholders?: Partial<StakeholderEntry>[];
  dataGaps?: string[];

  // Review metadata
  humanReviewFlags?: string[];   // Things the AI flagged as needing human judgment
  extractionNotes?: string;      // AI's overall commentary on extraction quality
}

// ── Decision Memory ──────────────────────────────────────────

/**
 * Persisted memory of what has been user-validated.
 * AI modules check this before generating anything —
 * if it's here and validated, do NOT regenerate.
 */
export interface DecisionMemory {
  strategies: string[];          // Strategy ids that are locked
  issues: string[];              // Issue ids that are locked
  stakeholders: string[];        // Stakeholder ids that are locked
  problemFrameValidated: boolean;
  lastUpdated: string;
}
